In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('test.csv')

In [12]:
df

,Unnamed: 0,中国石化,中信证券,三一重工,招商银行,保利发展,中国联通,特变电工,上汽集团,中国船舶,...,中国核电,中国银行,药明康德,海天味业,韦尔股份,兆易创新,中微公司,海光信息,金山办公,中芯国际
0,latest,6.480000,19.310000,16.240000,31.390000,8.080000,4.490000,11.960000,11.890000,33.900000,...,10.120000,4.690000,41.750000,36.280000,82.700000,65.130000,117.300000,75.510000,184.330000,43.430000
1,prediction,6.420828,19.321634,15.995324,30.923481,7.600364,4.488747,11.977072,11.709159,35.055275,...,9.878749,4.619624,40.024807,36.246723,84.419357,64.582733,123.022217,75.778946,181.540848,43.994572
2,rate,-0.009131,0.000603,-0.015066,-0.014862,-0.059361,-0.000279,0.001427,-0.015210,0.034079,...,-0.023839,-0.015006,-0.041322,-0.000917,0.020790,-0.008403,0.048783,0.003562,-0.015131,0.013000

In [13]:
def sz50():
    # 获取上证 50 成分股
    rs = bs.query_sz50_stocks()
    print('query_sz50 error_code:' + rs.error_code)
    print('query_sz50  error_msg:' + rs.error_msg)

    # 打印结果集
    sz50_stocks = []
    while (rs.error_code == '0') & rs.next():
        # 获取一条记录，将记录合并在一起
        sz50_stocks.append(rs.get_row_data())
    result = pd.DataFrame(sz50_stocks, columns=rs.fields)

    return result

In [14]:
import baostock as bs

bs.login()

sz50_stocks = sz50()

login success!
query_sz50 error_code:0
query_sz50  error_msg:success

In [15]:
sz50_stocks

    updateDate       code code_name
0   2024-09-16  sh.600028      中国石化
1   2024-09-16  sh.600030      中信证券
2   2024-09-16  sh.600031      三一重工
3   2024-09-16  sh.600036      招商银行
4   2024-09-16  sh.600048      保利发展
5   2024-09-16  sh.600050      中国联通
6   2024-09-16  sh.600089      特变电工
7   2024-09-16  sh.600104      上汽集团
8   2024-09-16  sh.600150      中国船舶
9   2024-09-16  sh.600276      恒瑞医药
10  2024-09-16  sh.600309      万华化学
11  2024-09-16  sh.600406      国电南瑞
12  2024-09-16  sh.600436       片仔癀
13  2024-09-16  sh.600438      通威股份
14  2024-09-16  sh.600519      贵州茅台
15  2024-09-16  sh.600690      海尔智家
16  2024-09-16  sh.600809      山西汾酒
17  2024-09-16  sh.600887      伊利股份
18  2024-09-16  sh.600900      长江电力
19  2024-09-16  sh.600941      中国移动
20  2024-09-16  sh.601012      隆基绿能
21  2024-09-16  sh.601088      中国神华
22  2024-09-16  sh.601166      兴业银行
23  2024-09-16  sh.601225      陕西煤业
24  2024-09-16  sh.601288      农业银行
25  2024-09-16  sh.601318      中国平安
26  2024-09-16  sh.601328      交通银行
27  2024-09-16  sh.601390      中国中铁
28  2024-09-16  sh.601398      工商银行
29  2024-09-16  sh.601601      中国太保
30  2024-09-16  sh.601628      中国人寿
31  2024-09-16  sh.601633      长城汽车
32  2024-09-16  sh.601658      邮储银行
33  2024-09-16  sh.601668      中国建筑
34  2024-09-16  sh.601669      中国电建
35  2024-09-16  sh.601728      中国电信
36  2024-09-16  sh.601857      中国石油
37  2024-09-16  sh.601888      中国中免
38  2024-09-16  sh.601899      紫金矿业
39  2024-09-16  sh.601919      中远海控
40  2024-09-16  sh.601985      中国核电
41  2024-09-16  sh.601988      中国银行
42  2024-09-16  sh.603259      药明康德
43  2024-09-16  sh.603288      海天味业
44  2024-09-16  sh.603501      韦尔股份
45  2024-09-16  sh.603986      兆易创新
46  2024-09-16  sh.688012      中微公司
47  2024-09-16  sh.688041      海光信息
48  2024-09-16  sh.688111      金山办公
49  2024-09-16  sh.688981      中芯国际

In [31]:
code = sz50_stocks['code'][0]


def get_stock(code: str):
    bs.login()

    rs = bs.query_history_k_data_plus(
        code=code,
        fields="date, code, open, high, low, close",
        start_date="2024-09-19",
        frequency="d",
        adjustflag="3"
    )

    # 打印结果集
    data_list = []
    while (rs.error_code == '0') & rs.next():
        # 获取一条记录，将记录合并在一起
        data_list.append(rs.get_row_data())

    result = pd.DataFrame(data_list, columns=rs.fields)

    bs.logout()

    return result.tail(1)

In [32]:
data = get_stock(code)

login success!
logout success!

In [33]:
data

         date       code    open    high     low   close
2  2024-09-23  sh.600028  6.4000  6.5400  6.3500  6.4800

In [93]:
import numpy as np
import pandas as pd
import baostock as bs

from read_all_stock import sz50

bs.login()

sz50_stocks = sz50()

real_price = []
last_price = []
for code in sz50_stocks['code']:
    rs = bs.query_history_k_data_plus(
        code=code,
        fields="date, code, open, high, low, close",
        start_date="2024-09-10",
        frequency="d",
        adjustflag="3"
    )

    # 打印结果集
    data_list = []
    while (rs.error_code == '0') & rs.next():
        # 获取一条记录，将记录合并在一起
        data_list.append(rs.get_row_data())

    result = pd.DataFrame(data_list, columns=rs.fields)

    latest = result.tail(1)
    last = result.tail(2)['close'].to_list()[0]
    real_price.append(latest['close'].to_list()[0])
    last_price.append(last)

bs.logout()

login success!
query_sz50 error_code:0
query_sz50  error_msg:success
logout success!

In [94]:
real_price = [float(p) for p in real_price]
last_price = [float(p) for p in last_price]

In [95]:
real_price, last_price

([6.48,
  19.31,
  16.24,
  31.39,
  8.08,
  4.49,
  11.96,
  11.89,
  33.9,
  42.71,
  75.65,
  25.64,
  197.77,
  17.43,
  1261.54,
  27.48,
  154.48,
  21.89,
  28.2,
  101.05,
  12.73,
  39.1,
  16.56,
  23.95,
  4.62,
  44.09,
  6.68,
  5.18,
  5.72,
  30.71,
  35.53,
  24.1,
  4.76,
  4.95,
  4.5,
  6.06,
  8.01,
  54.3,
  15.82,
  13.25,
  10.12,
  4.69,
  41.75,
  36.28,
  82.7,
  65.13,
  117.3,
  75.51,
  184.33,
  43.43],
 [6.38,
  19.29,
  15.85,
  30.94,
  8.05,
  4.49,
  12.04,
  11.86,
  33.88,
  42.71,
  75.67,
  25.74,
  201.0,
  17.81,
  1263.92,
  27.23,
  154.23,
  21.98,
  28.15,
  101.4,
  12.8,
  38.5,
  16.25,
  23.49,
  4.54,
  44.15,
  6.59,
  5.18,
  5.67,
  30.28,
  34.99,
  24.09,
  4.71,
  4.91,
  4.48,
  6.02,
  7.91,
  54.31,
  15.88,
  12.98,
  9.99,
  4.64,
  40.58,
  35.92,
  84.48,
  65.29,
  120.51,
  75.92,
  184.9,
  43.86])

In [96]:
df = pd.read_csv('test.csv', index_col=0)
# df['real_price'] = real_price

In [97]:
df = df.transpose()

In [98]:
df['real_price'] = real_price
df['latest'] = last_price

In [99]:
df['real_rate'] = df['real_price'] / df['latest'] - 1.0

In [100]:
df

,latest,prediction,rate,real_price,real_rate
中国石化,6.3800000000,6.4208283424,-0.0091314286,6.4800000000,0.0156739812
中信证券,19.2900000000,19.3216342926,0.0006025009,19.3100000000,0.0010368066
三一重工,15.8500000000,15.9953241348,-0.0150662479,16.2400000000,0.0246056782
招商银行,30.9400000000,30.9234809875,-0.0148620265,31.3900000000,0.0145442793
保利发展,8.0500000000,7.6003637314,-0.0593609243,8.0800000000,0.0037267081
中国联通,4.4900000000,4.4887471199,-0.0002790379,4.4900000000,0.0000000000
特变电工,12.0400000000,11.9770717621,0.0014274049,11.9600000000,-0.0066445183
上汽集团,11.8600000000,11.7091588974,-0.0152095124,11.8900000000,0.0025295110
中国船舶,33.8800000000,35.0552749634,0.0340789075,33.9000000000,0.0005903188
恒瑞医药,42.7100000000,44.7550735474,0.0478827803,42.7100000000,0.0000000000
万华化学,75.6700000000,74.4054794312,-0.0164510320,75.6500000000,-0.0002643055
国电南瑞,25.7400000000,25.7740421295,0.0052278522,25.6400000000,-0.0038850039
片仔癀,201.0000000000,197.2748565674,-0.0025036327,197.7700000000,-0.0160696517
通威股份,17.8100000000,18.2513065338,0.0471202831,17.4300000000,-0.0213363279
贵州茅台,1263.9200000000,1238.2281494141,-0.0184788834,1261.5400000000,-0.0018830306
海尔智家,27.2300000000,26.5355854034,-0.0343673434,27.4800000000,0.0091810503
山西汾酒,154.2300000000,150.4637603760,-0.0259984440,154.4800000000,0.0016209557
伊利股份,21.9800000000,22.0266113281,0.0062408099,21.8900000000,-0.0040946315
长江电力,28.1500000000,28.2584018707,0.0020709883,28.2000000000,0.0017761989
中国移动,101.4000000000,100.9250106812,-0.0012369057,101.0500000000,-0.0034516765
隆基绿能,12.8000000000,13.3122920990,0.0457417203,12.7300000000,-0.0054687500
中国神华,38.5000000000,38.3503189087,-0.0191734294,39.1000000000,0.0155844156
兴业银行,16.2500000000,16.1656875610,-0.0238111376,16.5600000000,0.0190769231
陕西煤业,23.4900000000,23.4595642090,-0.0204774861,23.9500000000,0.0195828012
农业银行,4.5400000000,4.5054593086,-0.0247923574,4.6200000000,0.0176211454
中国平安,44.1500000000,43.4529953003,-0.0144478272,44.0900000000,-0.0013590034
交通银行,6.5900000000,6.5833401680,-0.0144700347,6.6800000000,0.0136570561
中国中铁,5.1800000000,5.0441765785,-0.0262207377,5.1800000000,0.0000000000
工商银行,5.6700000000,5.6169071198,-0.0180232308,5.7200000000,0.0088183422
中国太保,30.2800000000,30.2090682983,-0.0163116803,30.7100000000,0.0142007926
中国人寿,34.9900000000,34.8544654846,-0.0190130739,35.5300000000,0.0154329809
长城汽车,24.0900000000,23.8509120941,-0.0103355978,24.1000000000,0.0004151100
邮储银行,4.7100000000,4.6787238121,-0.0170748294,4.7600000000,0.0106157113
中国建筑,4.9100000000,4.9308924675,-0.0038601076,4.9500000000,0.0081466395
中国电建,4.4800000000,4.3936357498,-0.0236365000,4.5000000000,0.0044642857
中国电信,6.0200000000,6.0137100220,-0.0076386102,6.0600000000,0.0066445183
中国石油,7.9100000000,8.0452117920,0.0043959790,8.0100000000,0.0126422250
中国中免,54.3100000000,54.1844711304,-0.0021276035,54.3000000000,-0.0001841282
紫金矿业,15.8800000000,15.8262310028,0.0003938687,15.8200000000,-0.0037783375
中远海控,12.9800000000,12.3687257767,-0.0665112621,13.2500000000,0.0208012327
中国核电,9.9900000000,9.8787488937,-0.0238390421,10.1200000000,0.0130130130
中国银行,4.6400000000,4.6196236610,-0.0150056160,4.6900000000,0.0107758621
药明康德,40.5800000000,40.0248069763,-0.0413219886,41.7500000000,0.0288319369
海天味业,35.9200000000,36.2467231750,-0.0009172223,36.2800000000,0.0100222717
韦尔股份,84.4800000000,84.4193572998,0.0207902938,82.7000000000,-0.0210700758
兆易创新,65.2900000000,64.5827331543,-0.0084026846,65.1300000000,-0.0024506050
中微公司,120.5100000000,123.0222167969,0.0487827519,117.3000000000,-0.0266367936
海光信息,75.9200000000,75.7789459229,0.0035617259,75.5100000000,-0.0054004215
金山办公,184.9000000000,181.5408477783,-0.0151312983,184.3300000000,-0.0030827474
中芯国际,43.8600000000,43.9945716858,0.0129995783,43.4300000000,-0.0098039216

In [101]:
def determine_sign(row):
    if row['rate'] > 0 and row['real_rate'] > 0:
        return 1
    elif row['rate'] < 0 and row['real_rate'] < 0:
        return 1
    elif row['rate'] > 0 and row['real_rate'] < 0:
        return -1
    elif row['rate'] < 0 and row['real_rate'] > 0:
        return -1
    else:
        return 0
    
df['accurate'] = df.apply(determine_sign, axis=1)

In [103]:
df

,latest,prediction,rate,real_price,real_rate,accurate
中国石化,6.3800000000,6.4208283424,-0.0091314286,6.4800000000,0.0156739812,-1
中信证券,19.2900000000,19.3216342926,0.0006025009,19.3100000000,0.0010368066,1
三一重工,15.8500000000,15.9953241348,-0.0150662479,16.2400000000,0.0246056782,-1
招商银行,30.9400000000,30.9234809875,-0.0148620265,31.3900000000,0.0145442793,-1
保利发展,8.0500000000,7.6003637314,-0.0593609243,8.0800000000,0.0037267081,-1
中国联通,4.4900000000,4.4887471199,-0.0002790379,4.4900000000,0.0000000000,0
特变电工,12.0400000000,11.9770717621,0.0014274049,11.9600000000,-0.0066445183,-1
上汽集团,11.8600000000,11.7091588974,-0.0152095124,11.8900000000,0.0025295110,-1
中国船舶,33.8800000000,35.0552749634,0.0340789075,33.9000000000,0.0005903188,1
恒瑞医药,42.7100000000,44.7550735474,0.0478827803,42.7100000000,0.0000000000,0
万华化学,75.6700000000,74.4054794312,-0.0164510320,75.6500000000,-0.0002643055,1
国电南瑞,25.7400000000,25.7740421295,0.0052278522,25.6400000000,-0.0038850039,-1
片仔癀,201.0000000000,197.2748565674,-0.0025036327,197.7700000000,-0.0160696517,1
通威股份,17.8100000000,18.2513065338,0.0471202831,17.4300000000,-0.0213363279,-1
贵州茅台,1263.9200000000,1238.2281494141,-0.0184788834,1261.5400000000,-0.0018830306,1
海尔智家,27.2300000000,26.5355854034,-0.0343673434,27.4800000000,0.0091810503,-1
山西汾酒,154.2300000000,150.4637603760,-0.0259984440,154.4800000000,0.0016209557,-1
伊利股份,21.9800000000,22.0266113281,0.0062408099,21.8900000000,-0.0040946315,-1
长江电力,28.1500000000,28.2584018707,0.0020709883,28.2000000000,0.0017761989,1
中国移动,101.4000000000,100.9250106812,-0.0012369057,101.0500000000,-0.0034516765,1
隆基绿能,12.8000000000,13.3122920990,0.0457417203,12.7300000000,-0.0054687500,-1
中国神华,38.5000000000,38.3503189087,-0.0191734294,39.1000000000,0.0155844156,-1
兴业银行,16.2500000000,16.1656875610,-0.0238111376,16.5600000000,0.0190769231,-1
陕西煤业,23.4900000000,23.4595642090,-0.0204774861,23.9500000000,0.0195828012,-1
农业银行,4.5400000000,4.5054593086,-0.0247923574,4.6200000000,0.0176211454,-1
中国平安,44.1500000000,43.4529953003,-0.0144478272,44.0900000000,-0.0013590034,1
交通银行,6.5900000000,6.5833401680,-0.0144700347,6.6800000000,0.0136570561,-1
中国中铁,5.1800000000,5.0441765785,-0.0262207377,5.1800000000,0.0000000000,0
工商银行,5.6700000000,5.6169071198,-0.0180232308,5.7200000000,0.0088183422,-1
中国太保,30.2800000000,30.2090682983,-0.0163116803,30.7100000000,0.0142007926,-1
中国人寿,34.9900000000,34.8544654846,-0.0190130739,35.5300000000,0.0154329809,-1
长城汽车,24.0900000000,23.8509120941,-0.0103355978,24.1000000000,0.0004151100,-1
邮储银行,4.7100000000,4.6787238121,-0.0170748294,4.7600000000,0.0106157113,-1
中国建筑,4.9100000000,4.9308924675,-0.0038601076,4.9500000000,0.0081466395,-1
中国电建,4.4800000000,4.3936357498,-0.0236365000,4.5000000000,0.0044642857,-1
中国电信,6.0200000000,6.0137100220,-0.0076386102,6.0600000000,0.0066445183,-1
中国石油,7.9100000000,8.0452117920,0.0043959790,8.0100000000,0.0126422250,1
中国中免,54.3100000000,54.1844711304,-0.0021276035,54.3000000000,-0.0001841282,1
紫金矿业,15.8800000000,15.8262310028,0.0003938687,15.8200000000,-0.0037783375,-1
中远海控,12.9800000000,12.3687257767,-0.0665112621,13.2500000000,0.0208012327,-1
中国核电,9.9900000000,9.8787488937,-0.0238390421,10.1200000000,0.0130130130,-1
中国银行,4.6400000000,4.6196236610,-0.0150056160,4.6900000000,0.0107758621,-1
药明康德,40.5800000000,40.0248069763,-0.0413219886,41.7500000000,0.0288319369,-1
海天味业,35.9200000000,36.2467231750,-0.0009172223,36.2800000000,0.0100222717,-1
韦尔股份,84.4800000000,84.4193572998,0.0207902938,82.7000000000,-0.0210700758,-1
兆易创新,65.2900000000,64.5827331543,-0.0084026846,65.1300000000,-0.0024506050,1
中微公司,120.5100000000,123.0222167969,0.0487827519,117.3000000000,-0.0266367936,-1
海光信息,75.9200000000,75.7789459229,0.0035617259,75.5100000000,-0.0054004215,-1
金山办公,184.9000000000,181.5408477783,-0.0151312983,184.3300000000,-0.0030827474,1
中芯国际,43.8600000000,43.9945716858,0.0129995783,43.4300000000,-0.0098039216,-1

In [105]:
# 统计 df['c'] 列中 1 和 -1 的个数
count_1 = (df['accurate'] == 1).sum()
count_neg1 = (df['accurate'] == -1).sum()

# 打印结果
print(f"1的个数: {count_1}")
print(f"-1的个数: {count_neg1}")

1的个数: 12
-1的个数: 35

In [106]:
12/(12+35)

0.2553191489361702